name: PR to Main - Tests

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run tests
        run: |
          pytest tests/unit/ -v --tb=short --cov=src/pewstats_collectors --cov-report=term-missing

      - name: Run linter
        run: |
          ruff check src/ tests/

      - name: Run formatter check
        run: |
          ruff format --check src/ tests/
