name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
          package-name: pewstats-collectors

  build-production:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Convert repository name to lowercase
        id: lowercase
        run: echo "repository=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Debug variables
        run: |
          echo "Repository: ${{ steps.lowercase.outputs.repository }}"
          echo "Tag: ${{ needs.release-please.outputs.tag_name }}"
          echo "Version: ${{ needs.release-please.outputs.version }}"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push production image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.lowercase.outputs.repository }}:${{ needs.release-please.outputs.tag_name }}
            ghcr.io/${{ steps.lowercase.outputs.repository }}:production
            ghcr.io/${{ steps.lowercase.outputs.repository }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ needs.release-please.outputs.tag_name }}

      - name: Summary
        run: |
          echo "## 🚀 Production Release" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** ${{ needs.release-please.outputs.tag_name }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Images:**" >> $GITHUB_STEP_SUMMARY
          echo "- \`ghcr.io/${{ steps.lowercase.outputs.repository }}:${{ needs.release-please.outputs.tag_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- \`ghcr.io/${{ steps.lowercase.outputs.repository }}:production\`" >> $GITHUB_STEP_SUMMARY
          echo "- \`ghcr.io/${{ steps.lowercase.outputs.repository }}:latest\`" >> $GITHUB_STEP_SUMMARY
